---
title: "South Park Exploratory Analysis"
author: "kwalker"
date: "January 27, 2016"
output: html_document
---

```{r opts, warning=FALSE, message=FALSE, echo=FALSE}
library(knitr)
library(stringr)
library(ggplot2)
library(RColorBrewer)
opts_chunk$set(cache=TRUE, fig.width=10, fig.height=8, echo=FALSE)
```


```{r}
#setwd("/Users/kaylinwalker/R/textmining_southpark/scripts")
#source("01_southpark_scrape.R") 
#source("02_southpark_corpus.R") 
#source("03_southpark_loglikelihood.R") 

setwd("/Users/kaylinwalker/R/textmining_southpark/tidy data")
ngrams <- read.csv("southpark_ngrams.csv", stringsAsFactors=FALSE)

main.speakers <- c("CARTMAN", "STAN", "KYLE", "KENNY", "RANDY", "BUTTERS", "MR..GARRISON")

ngrams <- ngrams[ngrams$LL >= 10.83, ] # 1073 / 21106 = 5%
ngrams.main <- ngrams[ngrams$speaker %in% main.speakers & ngrams$direction=="HIGH", ]

## remove redundant ngrams like "you guys" vs. "you guys i" and "guys you guys"
ngrams.norepeat <- ngrams[ngrams$ngram==1, ]
bi <- ngrams[ngrams$ngram == 2, ]
bi <- unique(bi$word)
for(h in seq_along(bi)) {
     for(s in main.speakers) {
          temp <- ngrams[grepl(bi[h], ngrams$word) & ngrams$speaker==s, ]
          if(length(temp[,1]) > 0 ) {
          temp <- temp[order(-temp$LL), ]          
          ngrams.norepeat <- rbind(ngrams.norepeat, temp[1,])
          }
     }
}
ngrams.norepeat <- unique(ngrams.norepeat)

ngrams.main.2 <- ngrams.norepeat[ngrams.norepeat$speaker %in% c("CARTMAN", "STAN", "KYLE", "KENNY")  & ngrams.norepeat$direction=="HIGH", ]
ggplot(ngrams.main.2, aes(speaker, log(LL))) + 
     geom_point(color="white") + 
     geom_text(aes(label=ngrams.main.2$word, size=log(ngrams.main.2$word.total), 
                   color=ngrams.main.2$speaker), alpha=0.75) + 
     scale_size(range=c(5,10)) +
     scale_color_brewer(palette="Paired") +
     theme_classic() + 
     theme(axis.text.x = element_text(angle = 20, hjust = 1), legend.position=1) + 
     labs(title="Most Characteristic Words & Phrases by Character") + 
     xlab("") + ylab("Log(Log Likelihood)")

```



